---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    networks:
      wireguard:
        ipv4_address: 10.0.0.1
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WG_HOST=vpn.yourdomain.tld
      - WG_PORT=51820
      - WG_CONFIG_PORT=51820
      - PASSWORD_HASH=PASSWORD_HASHED # docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD
      - WG_DEFAULT_DNS=1.1.1.1, 10.0.0.100
      - WG_ALLOWED_IPS=0.0.0.0/0, 192.168.1.0/24
      - WG_MTU=1400
    volumes:
      - ./config:/etc/wireguard
    restart: unless-stopped

networks:
  wireguard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
        # - subnet: fdcc:ad94:bacf:61a3::/64 # Uncomment for IPv6