---
services:
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: Europe/Paris
      WATCHTOWER_MONITOR_ONLY: "true" # Envoie uniquement d'une notification sans mise à jour automatique
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://<tokent>@<channel_id>" # https://discord.com/api/webhooks/<channel_id>/<token>
      WATCHTOWER_NO_RESTART: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
